/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * pic.java
 *
 * Created on Apr 21, 2013, 7:47:15 AM
 */
package cuepoints_picture;

/**
 *
 * @author AYYAPPA
 */
import cuelayer.Picture;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;        
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter; 
public class pic extends javax.swing.JFrame {
    String filename="";
    static int MAX;
    static int approved;
    ArrayList pctcollection;
    Picture pcp;

    /** Creates new form pic */
    public pic()  {
        MAX=10;
      initComponents();
      jLabel3.setText(MAX-approved+"");
     
        pctcollection=new ArrayList();
      
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        cuePointsIP = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(cuepoints_picture.CuePoints_PictureApp.class).getContext().getResourceMap(pic.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setBounds(new java.awt.Rectangle(40, 40, 0, 0));
        setMinimumSize(new java.awt.Dimension(673, 340));
        setName("Form"); // NOI18N
        getContentPane().setLayout(null);

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.setMinimumSize(new java.awt.Dimension(230, 150));
        jLabel1.setName("jLabel1"); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(640, 480));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(400, 60, 230, 150);

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(160, 70, 120, 40);

        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(10, 70, 120, 40);

        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(10, 250, 210, 40);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        cuePointsIP.setColumns(20);
        cuePointsIP.setRows(5);
        cuePointsIP.setName("cuePointsIP"); // NOI18N
        jScrollPane1.setViewportView(cuePointsIP);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 120, 370, 120);

        jButton4.setText(resourceMap.getString("jButton4.text")); // NOI18N
        jButton4.setName("jButton4"); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(500, 250, 110, 40);

        jButton5.setText(resourceMap.getString("jButton5.text")); // NOI18N
        jButton5.setName("jButton5"); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(240, 250, 200, 40);

        jLabel3.setFont(resourceMap.getFont("jLabel3.font")); // NOI18N
        jLabel3.setForeground(resourceMap.getColor("jLabel3.foreground")); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(600, 10, 50, 40);

        jPanel1.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        jLabel2.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        jPanel1.add(jLabel2);

        jLabel4.setFont(resourceMap.getFont("jLabel4.font")); // NOI18N
        jLabel4.setForeground(resourceMap.getColor("jLabel4.foreground")); // NOI18N
        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        jPanel1.add(jLabel4);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 670, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents
 private void updateCuePoints()
    {

        cuePointsIP.setText("");
     for(int i=0;i<pctcollection.size();i++)
     {
         cuePointsIP.append(pctcollection.get(i) + "\r\n");
     }
    
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         pctcollection.add(filename);
       jLabel3.setText(MAX-approved+"");
        JOptionPane.showMessageDialog(this,"PICTURE SAVED");
        approved++;
            
              if(approved>=MAX)
        {
            JOptionPane.showMessageDialog(this,"IMAGE INDEX COMPLETED NOW YOU CAN REGISTER");
            jButton1.setEnabled(false);
             jButton2.setEnabled(false);
            return;
        }
    updateCuePoints();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JFileChooser jfc=new JFileChooser();      
        FileNameExtensionFilter ext=new FileNameExtensionFilter("Image Files", "JPG");
        jfc.setFileFilter(ext); //Sets the current file filter. The file filter is used by the file chooser to filter out files from the user's view.
        int rc=jfc.showOpenDialog(this);
        if(rc==JFileChooser.APPROVE_OPTION)
        {
            filename=jfc.getSelectedFile().getAbsolutePath();
        ImageIcon ic=new ImageIcon(jfc.getSelectedFile().getAbsolutePath());
        Image img=ic.getImage();
      Image modified= img.getScaledInstance(230, 150,2);
       ic=new ImageIcon(modified);
      jLabel1.setIcon(ic);
            
    }//GEN-LAST:event_jButton2ActionPerformed
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        pcp=new Picture(pctcollection);
boolean result=pcp.insertData();
if(result)
    
    JOptionPane.showMessageDialog(this,"PICTURES Successfully INSERTED");
else
    JOptionPane.showMessageDialog(this,"PICTURES not Successfully INSERTED");
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        MainMenu mn=new MainMenu();
        mn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        pcp.truncate();
        JOptionPane.showMessageDialog(this,"PICTURES Successfully DELETED");
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new pic().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea cuePointsIP;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
